// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phone_Forecast.Models.DbContexts;

namespace Phone_Forecast.Data.Migrations.Hardware
{
    [DbContext(typeof(HardwareContext))]
    [Migration("20200311154348_Hardware1")]
    partial class Hardware1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phone_Forecast.Models.DbContexts.Hardware", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatteryCapacity");

                    b.Property<bool>("CanRecordVideo");

                    b.Property<int>("Cpu");

                    b.Property<double>("Depth");

                    b.Property<int>("FrontCameraMegapixel");

                    b.Property<int>("GPU");

                    b.Property<bool>("Has2g");

                    b.Property<bool>("Has3g");

                    b.Property<bool>("Has4g");

                    b.Property<bool>("Has5g");

                    b.Property<bool>("HasBluetooth");

                    b.Property<bool>("HasDualSim");

                    b.Property<bool>("HasExchangableBattery");

                    b.Property<bool>("HasFastCharging");

                    b.Property<bool>("HasFrontCamera");

                    b.Property<bool>("HasGPU");

                    b.Property<bool>("HasGps");

                    b.Property<bool>("HasHeadphoneOutput");

                    b.Property<bool>("HasMemoryCardReader");

                    b.Property<bool>("HasRearCamera");

                    b.Property<bool>("HasWifi");

                    b.Property<bool>("HasWirelessCharging");

                    b.Property<double>("Height");

                    b.Property<int>("InternalStorageSpace");

                    b.Property<bool>("IsSelected");

                    b.Property<bool>("IsWaterResistant");

                    b.Property<int>("MaxFramerateMaxResolution");

                    b.Property<int>("MaxFramerateMinResolution");

                    b.Property<double>("MaximumLensAperture");

                    b.Property<double>("OriginalPrice");

                    b.Property<int>("PhoneModel");

                    b.Property<int>("ProcessorCoreCount");

                    b.Property<double>("ProcessorCoreSpeed");

                    b.Property<string>("ProductPage")
                        .HasMaxLength(256);

                    b.Property<int>("RAM");

                    b.Property<int>("RearCameraCount");

                    b.Property<int>("RearCameraMegapixel");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<int>("SimCard");

                    b.Property<double>("Weight");

                    b.Property<double>("Width");

                    b.Property<int>("WirelessStandard");

                    b.HasKey("ConfigId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
